### ISSUE TITLE
Getting Oops... Unauthorized after signup

### ISSUE THREAD

**Issue by resting** [auth0-samples/auth0-react-samples#206] opened 2020-07-25 17:43 UTC
Downloaded the sample and did `npm i` and `npm start`.
Was able to sign up and sign in successfully according to the logs.

However, after clicking on the green tick when prompted to grant permission, it kept display a blank page with `Oops... Unauthorized`.

Log type `Failed Exchange`

Log as below:
```
{
  "date": "2020-07-25T17:37:08.413Z",
  "type": "feacft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": "--removed--
  "client_name": null,
  "ip": "101.127.6.165",
  "user_agent": "Chrome 84.0.4147 / Mac OS X 10.15.5",
  "details": {
    "code": "*************BA6"
  },
  "hostname": "--removed--",
  "user_id": "",
  "user_name": "",
  "log_id": "90020200725173713598000178280607258323126144419732914178",
  "_id": "90020200725173713598000178280607258323126144419732914178",
  "isMobile": false
}
```

**Comment by haukened** [comment] 2020-07-29 01:38
I also have this issue.

**Comment by stevehobbsdev** [comment] 2020-07-30 10:09
@resting Please ensure that you have filled in the "Allowed Web Origins" field when setting up your Auth0 client - this is necessary for the app to work.

https://auth0.com/docs/quickstart/spa/react#configure-allowed-web-origins

**Comment by meetsreekanth** [comment] 2020-08-05 19:16
I have the same issue. I just downloaded the sample, updated the config and ran it. the app logs in but fails with a page "error .. unauthorized"

checking the logs in auth0 i see two entries 

![image](https://user-images.githubusercontent.com/7451319/89454381-7c6c9f80-d715-11ea-93eb-36fa8f5a7040.png)

**Comment by jlek** [comment] 2020-08-06 15:44
I'm also getting this issue. @stevehobbsdev I did add `http://localhost:3000` to "Allowed Web Origins" (as well as to "Allowed Callback URLs" and "Allowed Logout URLs". I see the same logs as @meetsreekanth.

**Comment by jerry2971** [comment] 2020-08-21 07:42
I have the same issue with using `Default App`, but it's work with a new application.

**Comment by ouchxp** [comment] 2020-08-30 02:54
> Hey all,
> 
> We do have a known issue when you're using the Default App as supplied with a new tenant. Please could you try the following.
> 
> Either:
> 
>     * Create a new application, ensure it is a Single Page Application type and that the Token Endpoint Authentication Mode setting is "None"
> 
>     * Modify your existing Default App so that Token Endpoint Authentication Mode is set to "None". For SPAs, this option is normally disabled, so you may need to change to a different application type, change this setting and then set it back to SPA again.
> 
> 
> ![image](https://user-images.githubusercontent.com/766403/90913594-5fea8b80-e3d4-11ea-901e-238bc627c42a.png)
> 
> Let me know if that works or doesn't make sense.

This worked for me! Thanks!

**Comment by stevehobbsdev** [comment] 2020-08-31 11:13
Thanks!

Closing this for now as it's a known issue we're dealing with on the server side and the fix is posted above. Would be good to continue to hear from people where the fix does not work.

**Closed by stevehobbsdev** 2020-08-31 11:13 UTC

**Comment by mrquincle** [comment] 2020-10-25 14:20
I would recommend to create a new account and run your own example. This is my on-boarding experience till now:

1. As a new user I have of course the "Default App". 
2. Start at https://auth0.com/docs/quickstart/spa/react downloading the code. The site works fine locally, but the login feature doesn't work. It's complaining about the default value in the `audience` field. Okay, figuring out on the next page https://auth0.com/docs/quickstart/spa/react/02-calling-an-api what to fill in there. 
3. After logging in with two different methods (because I read somewhere that the social login with Google might not work) I still get `Oops... Unauthorized`. 
4. Quite a lot of the code is not the same as with the example app I have downloaded. Weird, why is it not updated? I see `ProfileComponent` rather than `Profile`, etc.
5. Start hunting down the above cryptic message on the internet and ending up here. It doesn't work with "Default App"... Mmm... That's not the on-boarding experience you want to have. If that's the case, make sure someone first creates a new app and disallow the "Default App" from the drop-down box in the beginning.

I have now solved it by indeed changing the settings in "Default App" as described:

- Token Endpoint Authentication Method is **disabled**
- Change Application Type to **Regular Web Application**, this enables the above option
- Change Token Endpoint Authentication Method to **None**.
- Change Application Type to **Single Page Application**, don't forget to save.

I have the feeling auth0 was really good in the onboarding experience, but there are no resources anymore for this. Please, use my extended comment as hopefully constructive feedback. I'm not a disgruntled user. I'm honestly just a bit surprised (also on this issue just being closed).

**Comment by sswam** [comment] 2024-01-10 14:02
This onboarding issue for SPAs was closed in 2020, but it's still a problem today in 2024.

**Comment by Jay1305** [comment] 2024-04-01 22:09
I received the same error today while working for the first time with react + auth0. You need to switch to credentials tab of your default app and set **Authentication Methods** to None (which by default gets set to "Client Secret (Post)". Just putting here if anybody comes in the situation as me. 

![image](https://github.com/auth0-samples/auth0-react-samples/assets/31636584/c2dd778d-375d-4122-9277-d95fdb2c39db)

**Comment by petar-ps** [comment] 2024-06-11 10:50
@jaypan13  thank you ser, i lost 2h trying to solve this as a new noob user to auth0. They should update their tutorial example with more user friendly explanation.

**Comment by ashenoy25** [comment] 2025-02-27 00:07
I just tried this in Feb 2025 and the issue is still happening.  The workaround presented as a solution fixes the problem but very surprised to see that Auth0 still has not fixed this after it being initially reported almost 5 years back.
